"use client";

import { useState } from "react";
import { Outfit } from "next/font/google";
import "./globals.css";

import Sidebar from "../components/sidebar";
import Header from "../components/header/header";

const geistSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <head>
        <title>Daniel Hall - Software Solutions Architect</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Daniel Hall - Software Solutions Architect" />
        <meta name="keywords" content="Daniel Hall, Software Solutions Architect, Full Stack Developer, .NET Developer, Next.js, React, TypeScript, JavaScript, Azure, BigCommerce, Storyblok" />
        <meta name="author" content="Daniel Hall" />
      </head>
      <body className={geistSans.variable}>
        <div className="flex h-screen font-geistSans">
          <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen}/>
          {/* Main Content */}
          <main className="flex-1 bg-background overflow-y-auto px-6 pt-6 sm:pt-10 lg:pt-3 pb-12">
            <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen}/>
            <div className="container pt-2 px-4">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}


