"use client";

import type { Metadata } from "next";
import { useState } from "react";
import { Outfit } from "next/font/google";
import "./globals.css";

import Sidebar from "../components/sidebar";
import Header from "../components/header/header";

const geistSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <div className="flex h-screen font-geistSans">
          <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen}/>
          {/* Main Content */}
          <main className="flex-1 p-6 bg-background overflow-y-auto ml-0 md:mt-20">
            <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen}/>
            <div className="container p-4">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}


